version: "3.2"

# list of containers to be run
services:

  # rabbit_mq container uses the default rabbitmq image
  # exposes the ports
  # uses the specified volume
  rabbit_mq:
    # we use management image to get the
    # plugin for web dashboard
    image: rabbitmq:latest
    container_name: rabbit_mq
    ports:
        - '5672:5672'
        - '15672:15672'
    volumes:
      - rabbit_mqdata:/usr/share/rabbitmq/data
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30

  # rpc broker container
  rpc_broker:
    build:
      context: .
      args:
        ik_method: 'ann'
        ann_model: 'models/roboarm_model_1674153800-982793.h5'
    depends_on:
      rabbit_mq:
        condition: service_healthy
    environment:
        AMQP_URL: 'amqp://rabbit_mq?connection_attempts=10&retry_delay=10'
    volumes:
      - /usr/src/app/inversekine/rpc_broker


volumes:
    rabbit_mqdata:
      driver: local